### ISSUE TITLE
Connecting to VM over port 22 is blocked by DenyHighRisk rule

### ISSUE THREAD

**Issue by crouchcd** [STRIDES/NIHCloudLabAzure#80]
I have followed the steps described in [Virtual-machine-best-practices.md](https://github.com/STRIDES/NIHCloudLabAzure/blob/main/docs/Virtual-machine-best-practices.md)

I expect to be able to connect via SSH, but I am blocked by the DenyHighRisk rule. I have verified that even NIH network is blocked from port 22.

![Screenshot 2024-03-14 at 8 58 27 AM](https://github.com/STRIDES/NIHCloudLabAzure/assets/19394466/dcbdd667-29c0-4c8a-aaf0-d7752313c0b9)

Please help! Thanks!

**Comment by kyleoconnell-NIH** [comment]
Got it, we will look into this and get back shortly.

**Comment by kyleoconnell-NIH** [comment]
Please try again when on the VPN or on campus. If that doesn't work let me know.

**Comment by crouchcd** [comment]
@kyleoconnell-NIH That fixed it, thanks!
