### ISSUE TITLE
Azure Fix Link Checker

### ISSUE THREAD

**Issue by zbyosufzai** [STRIDES/NIHCloudLabAzure#86]
link checker shows false alert 

https://github.com/STRIDES/NIHCloudLabAzure/blob/main/.github/workflows/check_links.yml

**Comment by furniturewalatkNIH** [comment]
Ok looking through all the runs of this , I see that run #100 of this workflow https://github.com/STRIDES/NIHCloudLabAzure/actions/runs/8194944696 was the last successful one. 
( About a month ago on Mar/7).

And now I see/recollect the issue/false alert.

Its reporting/finding this as an error - https://github.com/STRIDES/NIHCloudLabAzure/tree/main/ /   whereas the working link is https://github.com/STRIDES/NIHCloudLabAzure/tree/main/notebooks/GenAI/  ( with a front slash in between notebooks and GenAI. 

I did a command+F search on the raw README.md and I dont see a match for it that way - over there its with the correct format ie "notebooks/GenAI" - wonder why the tool is suddenly seeing this wrongly?

**Comment by furniturewalatkNIH** [comment]
Created a PR to fix this issue.  
We can see that the 'false alerts' being shown in run 189 https://github.com/STRIDES/NIHCloudLabAzure/actions/runs/8616801573  are now not seen in run 190 https://github.com/STRIDES/NIHCloudLabAzure/actions/runs/8648945976/job/23714027770 

Need to verify the new ones being shown if they are valid or not.

**Comment by furniturewalatkNIH** [comment]
Have merged the PR into main to fix the 404 ( Not Found error) issue.

However I still see some dead links with a 403 ( Permission issue)  - though on clicking the links outside , I can reach/see them. 
Will need to further investigate what this is.

FYI @zbyosufzai

**Comment by furniturewalatkNIH** [comment]
On further research it appears that some websites explicitly reject automated api checks/requests/crawls and may send back a 403, whereas a regular human via browser will be able to reach/see it. 
This is probably the case with the niad-immune-response link 403 too eg https://www.[niaid.nih.gov/robots.txt.

Thus for now have excluded  403's - The PR for it has been merged. 

The link-checker is green and working fine now :-) 
Shall be closing this issue as resolved. 


@zbyosufzai  @kyleoconnell-NIH
